version: '3.9'
services:
  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
    image: docker.pkg.github.com/itsaln/purple-next/purple-next:develop
    container_name: purple-next
    restart: always
    ports:
      - 3000:3000
#    volumes:
#      - /data.env:data/.env